### ISSUE TITLE
A32nx with fs2crew at EDDM had multiple apu start/stop events during pre-flight

### ISSUE THREAD

**Issue by sushiat** [opensky-to/agent-msfs#14]
APU was started and avail, bleed was off ... no other change or sim pause

**Comment by markuskorbel** [comment]
![image](https://user-images.githubusercontent.com/6118673/142660524-69dea47a-07fb-4213-8d44-3ebdea757da6.png)

**Comment by markuskorbel** [comment]
I read somewhere recently on an issue on the A32nx project about this, check with latest version to see if this is fixed

**Comment by sushiat** [comment]
This is an issue with the A32NX mod and not the OpenSky agent
